#!/usr/bin/env bash
# vim: set autoindent smartindent ts=4 sw=4 sts=4 noet filetype=sh:

if [[ "$OSTYPE" == "msys" || "$OSTYPE" == "cygwin" || -n "$COMSPEC" ]]; then
	if command -v gmake > /dev/null 2>&1 || command -v make > /dev/null 2>&1; then
		function refresh-dotfiles
		{
			if [[ ! -v WHENCE_CMD ]]; then
				local -a WHENCE_CMD
				if [[ -v BASH_VERSION ]]; then
					WHENCE_CMD=(builtin type -P)
				elif [[ -v ZSH_VERSION ]]; then
					WHENCE_CMD=(builtin whence -p)
				fi
			fi
			local MAKE_CMD=make
			"${WHENCE_CMD[@]}" gmake > /dev/null 2>&1 && MAKE_CMD=gmake
			"$MAKE_CMD" -C "$HOME/.dotfiles" install
		}
	fi
	return
fi

function refresh-dotfiles
{
	if [[ ! -v WHENCE_CMD ]]; then
		local -a WHENCE_CMD
		if [[ -v BASH_VERSION ]]; then
			WHENCE_CMD=(builtin type -P)
		elif [[ -v ZSH_VERSION ]]; then
			WHENCE_CMD=(builtin whence -p)
		fi
	fi
	local TGTDIR="${SHELLRCDIR:-$HOME}"
	local MYBRCD="$TGTDIR/.dotfiles"
	local UPSTREAM_BASE=/dev/null
	[[ -n "$SUDO_USER" ]] && UPSTREAM_BASE=$(eval echo ~$SUDO_USER)
	local UPSTREAM_LOCDOTFI="$UPSTREAM_BASE/.local/dotfiles"
	local UPSTREAM_DOTFILES="$UPSTREAM_BASE/.dotfiles"
	[[ -d "$TGTDIR/.ssh" ]] || mkdir "$TGTDIR/.ssh"
	[[ -d "$MYBRCD" ]] || { echo "ERROR: $MYBRCD missing or not a directory."; return; }
	if [[ -d "$UPSTREAM_LOCDOTFI/.hg" && -x "$UPSTREAM_LOCDOTFI/refresh-dotfiles" && "$1" != "--nopull" ]]; then
		(export UPSTREAM_REPO="$UPSTREAM_LOCDOTFI"; set -x; cd "$UPSTREAM_LOCDOTFI" && ./refresh-dotfiles)
	elif [[ -d "$UPSTREAM_LOCDOTFI/.git" && -x "$UPSTREAM_LOCDOTFI/refresh-dotfiles" && "$1" != "--nopull" ]]; then
		(export UPSTREAM_REPO="$UPSTREAM_LOCDOTFI"; set -x; cd "$UPSTREAM_LOCDOTFI" && ./refresh-dotfiles)
	fi
	echo "Refreshing $MYBRCD from default pull location"
	if [[ -d "$MYBRCD/.hg" ]]; then
		[[ "$MYBRCD/hgrc.local" -nt "$MYBRCD/.hg/hgrc" ]] && cp -a "$MYBRCD/hgrc.local" "$MYBRCD/.hg/hgrc"
		[[ "$1" == "--nopull" ]] || ([[ -d "$UPSTREAM_DOTFILES/.hg" ]] && export UPSTREAM_REPO="$UPSTREAM_DOTFILES"; set -x; "${WHENCE_CMD[@]}" hg 2> /dev/null && hg -R "$MYBRCD" pull -u ${UPSTREAM_REPO:-} || hg up -R "$MYBRCD")
	fi
	local GMAKE=make
	"${WHENCE_CMD[@]}" gmake 2> /dev/null && GMAKE=gmake
	if [[ -e "$MYBRCD/GNUmakefile" ]]; then
		if ( $GMAKE --no-print-directory -C "$MYBRCD" TGTDIR="$TGTDIR" install ); then
			if [[ -n "$ZSH_VERSION" ]]; then
				source "$TGTDIR/.zshrc"
			else
				source "$TGTDIR/.bash_profile"
			fi
			cd -
		fi
	fi
}
